export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const FETCH_PAYIN_TRANSACTIONS_REQUEST =
  "FETCH_PAYIN_TRANSACTIONS_REQUEST";
export const FETCH_PAYIN_TRANSACTIONS_SUCCESS =
  "FETCH_PAYIN_TRANSACTIONS_SUCCESS";
export const FETCH_PAYIN_TRANSACTIONS_FAILURE =
  "FETCH_PAYIN_TRANSACTIONS_FAILURE";
export const SET_LOADING = false;

// export const FETCH_PAYIN_TRANSACTIONS = "FETCH_PAYIN_TRANSACTIONS";
